//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoVenta.WS_Info {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioVO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UsuarioVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EquipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Equipo {
            get {
                return this.EquipoField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipoField, value) != true)) {
                    this.EquipoField = value;
                    this.RaisePropertyChanged("Equipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoVO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProductoVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ConsecutivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenciaAnteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagenDerechaField;
        
        private decimal Precio_VentaField;
        
        private decimal CostoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoBarrasField;
        
        private int CantidadField;
        
        private decimal TotalUnitarioField;
        
        private short PromocionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Consecutivo {
            get {
                return this.ConsecutivoField;
            }
            set {
                if ((this.ConsecutivoField.Equals(value) != true)) {
                    this.ConsecutivoField = value;
                    this.RaisePropertyChanged("Consecutivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Referencia {
            get {
                return this.ReferenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenciaField, value) != true)) {
                    this.ReferenciaField = value;
                    this.RaisePropertyChanged("Referencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReferenciaAnterior {
            get {
                return this.ReferenciaAnteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenciaAnteriorField, value) != true)) {
                    this.ReferenciaAnteriorField = value;
                    this.RaisePropertyChanged("ReferenciaAnterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ImagenDerecha {
            get {
                return this.ImagenDerechaField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenDerechaField, value) != true)) {
                    this.ImagenDerechaField = value;
                    this.RaisePropertyChanged("ImagenDerecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public decimal Precio_Venta {
            get {
                return this.Precio_VentaField;
            }
            set {
                if ((this.Precio_VentaField.Equals(value) != true)) {
                    this.Precio_VentaField = value;
                    this.RaisePropertyChanged("Precio_Venta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public decimal Costo {
            get {
                return this.CostoField;
            }
            set {
                if ((this.CostoField.Equals(value) != true)) {
                    this.CostoField = value;
                    this.RaisePropertyChanged("Costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string CodigoBarras {
            get {
                return this.CodigoBarrasField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoBarrasField, value) != true)) {
                    this.CodigoBarrasField = value;
                    this.RaisePropertyChanged("CodigoBarras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public decimal TotalUnitario {
            get {
                return this.TotalUnitarioField;
            }
            set {
                if ((this.TotalUnitarioField.Equals(value) != true)) {
                    this.TotalUnitarioField = value;
                    this.RaisePropertyChanged("TotalUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public short Promocion {
            get {
                return this.PromocionField;
            }
            set {
                if ((this.PromocionField.Equals(value) != true)) {
                    this.PromocionField = value;
                    this.RaisePropertyChanged("Promocion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProveedorVO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProveedorVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ConsecutivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Consecutivo {
            get {
                return this.ConsecutivoField;
            }
            set {
                if ((this.ConsecutivoField.Equals(value) != true)) {
                    this.ConsecutivoField = value;
                    this.RaisePropertyChanged("Consecutivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nit {
            get {
                return this.NitField;
            }
            set {
                if ((object.ReferenceEquals(this.NitField, value) != true)) {
                    this.NitField = value;
                    this.RaisePropertyChanged("Nit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Compra", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Compra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProveedorField;
        
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string facturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PuntoVenta.WS_Info.ProductoVO[] ProductosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Proveedor {
            get {
                return this.ProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.ProveedorField, value) != true)) {
                    this.ProveedorField = value;
                    this.RaisePropertyChanged("Proveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string factura {
            get {
                return this.facturaField;
            }
            set {
                if ((object.ReferenceEquals(this.facturaField, value) != true)) {
                    this.facturaField = value;
                    this.RaisePropertyChanged("factura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public PuntoVenta.WS_Info.ProductoVO[] Productos {
            get {
                return this.ProductosField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductosField, value) != true)) {
                    this.ProductosField = value;
                    this.RaisePropertyChanged("Productos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VentaVO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VentaVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Numero_ventaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarrioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentariosField;
        
        private short EnvioField;
        
        private short PagoField;
        
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionEnvioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionPagoField;
        
        private short TarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PuntoVenta.WS_Info.ProductoVO[] ProductosField;
        
        private short PuntoVentaField;
        
        private decimal TotalVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Numero_venta {
            get {
                return this.Numero_ventaField;
            }
            set {
                if ((this.Numero_ventaField.Equals(value) != true)) {
                    this.Numero_ventaField = value;
                    this.RaisePropertyChanged("Numero_venta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NombreCliente {
            get {
                return this.NombreClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreClienteField, value) != true)) {
                    this.NombreClienteField = value;
                    this.RaisePropertyChanged("NombreCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Barrio {
            get {
                return this.BarrioField;
            }
            set {
                if ((object.ReferenceEquals(this.BarrioField, value) != true)) {
                    this.BarrioField = value;
                    this.RaisePropertyChanged("Barrio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Comentarios {
            get {
                return this.ComentariosField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentariosField, value) != true)) {
                    this.ComentariosField = value;
                    this.RaisePropertyChanged("Comentarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public short Envio {
            get {
                return this.EnvioField;
            }
            set {
                if ((this.EnvioField.Equals(value) != true)) {
                    this.EnvioField = value;
                    this.RaisePropertyChanged("Envio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public short Pago {
            get {
                return this.PagoField;
            }
            set {
                if ((this.PagoField.Equals(value) != true)) {
                    this.PagoField = value;
                    this.RaisePropertyChanged("Pago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string DescripcionEnvio {
            get {
                return this.DescripcionEnvioField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionEnvioField, value) != true)) {
                    this.DescripcionEnvioField = value;
                    this.RaisePropertyChanged("DescripcionEnvio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string DescripcionPago {
            get {
                return this.DescripcionPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionPagoField, value) != true)) {
                    this.DescripcionPagoField = value;
                    this.RaisePropertyChanged("DescripcionPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public short Tarjeta {
            get {
                return this.TarjetaField;
            }
            set {
                if ((this.TarjetaField.Equals(value) != true)) {
                    this.TarjetaField = value;
                    this.RaisePropertyChanged("Tarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public PuntoVenta.WS_Info.ProductoVO[] Productos {
            get {
                return this.ProductosField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductosField, value) != true)) {
                    this.ProductosField = value;
                    this.RaisePropertyChanged("Productos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public short PuntoVenta {
            get {
                return this.PuntoVentaField;
            }
            set {
                if ((this.PuntoVentaField.Equals(value) != true)) {
                    this.PuntoVentaField = value;
                    this.RaisePropertyChanged("PuntoVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public decimal TotalVenta {
            get {
                return this.TotalVentaField;
            }
            set {
                if ((this.TotalVentaField.Equals(value) != true)) {
                    this.TotalVentaField = value;
                    this.RaisePropertyChanged("TotalVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string Archivo {
            get {
                return this.ArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivoField, value) != true)) {
                    this.ArchivoField = value;
                    this.RaisePropertyChanged("Archivo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaVentaVO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ConsultaVentaVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long Numero_VentaField;
        
        private long Numero_DetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClienteField;
        
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarrioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnvioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductoField;
        
        private int CantidadField;
        
        private decimal PrecioField;
        
        private decimal TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Numero_Venta {
            get {
                return this.Numero_VentaField;
            }
            set {
                if ((this.Numero_VentaField.Equals(value) != true)) {
                    this.Numero_VentaField = value;
                    this.RaisePropertyChanged("Numero_Venta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long Numero_Detalle {
            get {
                return this.Numero_DetalleField;
            }
            set {
                if ((this.Numero_DetalleField.Equals(value) != true)) {
                    this.Numero_DetalleField = value;
                    this.RaisePropertyChanged("Numero_Detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Barrio {
            get {
                return this.BarrioField;
            }
            set {
                if ((object.ReferenceEquals(this.BarrioField, value) != true)) {
                    this.BarrioField = value;
                    this.RaisePropertyChanged("Barrio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Comentarios {
            get {
                return this.ComentariosField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentariosField, value) != true)) {
                    this.ComentariosField = value;
                    this.RaisePropertyChanged("Comentarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Envio {
            get {
                return this.EnvioField;
            }
            set {
                if ((object.ReferenceEquals(this.EnvioField, value) != true)) {
                    this.EnvioField = value;
                    this.RaisePropertyChanged("Envio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Pago {
            get {
                return this.PagoField;
            }
            set {
                if ((object.ReferenceEquals(this.PagoField, value) != true)) {
                    this.PagoField = value;
                    this.RaisePropertyChanged("Pago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public decimal Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Archivo {
            get {
                return this.ArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivoField, value) != true)) {
                    this.ArchivoField = value;
                    this.RaisePropertyChanged("Archivo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Info.WS_InfoSoap")]
    public interface WS_InfoSoap {
        
        // CODEGEN: Generating message contract since element name _token from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarProductos", ReplyAction="*")]
        PuntoVenta.WS_Info.ConsultarProductosResponse ConsultarProductos(PuntoVenta.WS_Info.ConsultarProductosRequest request);
        
        // CODEGEN: Generating message contract since element name _token from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarProveedores", ReplyAction="*")]
        PuntoVenta.WS_Info.ConsultarProveedoresResponse ConsultarProveedores(PuntoVenta.WS_Info.ConsultarProveedoresRequest request);
        
        // CODEGEN: Generating message contract since element name _token from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CompraNueva", ReplyAction="*")]
        PuntoVenta.WS_Info.CompraNuevaResponse CompraNueva(PuntoVenta.WS_Info.CompraNuevaRequest request);
        
        // CODEGEN: Generating message contract since element name _token from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VentaNueva", ReplyAction="*")]
        PuntoVenta.WS_Info.VentaNuevaResponse VentaNueva(PuntoVenta.WS_Info.VentaNuevaRequest request);
        
        // CODEGEN: Generating message contract since element name ConsultarVentasResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarVentas", ReplyAction="*")]
        PuntoVenta.WS_Info.ConsultarVentasResponse ConsultarVentas(PuntoVenta.WS_Info.ConsultarVentasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarProductos", Namespace="http://tempuri.org/", Order=0)]
        public PuntoVenta.WS_Info.ConsultarProductosRequestBody Body;
        
        public ConsultarProductosRequest() {
        }
        
        public ConsultarProductosRequest(PuntoVenta.WS_Info.ConsultarProductosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarProductosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PuntoVenta.WS_Info.UsuarioVO _token;
        
        public ConsultarProductosRequestBody() {
        }
        
        public ConsultarProductosRequestBody(PuntoVenta.WS_Info.UsuarioVO _token) {
            this._token = _token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarProductosResponse", Namespace="http://tempuri.org/", Order=0)]
        public PuntoVenta.WS_Info.ConsultarProductosResponseBody Body;
        
        public ConsultarProductosResponse() {
        }
        
        public ConsultarProductosResponse(PuntoVenta.WS_Info.ConsultarProductosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarProductosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PuntoVenta.WS_Info.ProductoVO[] ConsultarProductosResult;
        
        public ConsultarProductosResponseBody() {
        }
        
        public ConsultarProductosResponseBody(PuntoVenta.WS_Info.ProductoVO[] ConsultarProductosResult) {
            this.ConsultarProductosResult = ConsultarProductosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarProveedoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarProveedores", Namespace="http://tempuri.org/", Order=0)]
        public PuntoVenta.WS_Info.ConsultarProveedoresRequestBody Body;
        
        public ConsultarProveedoresRequest() {
        }
        
        public ConsultarProveedoresRequest(PuntoVenta.WS_Info.ConsultarProveedoresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarProveedoresRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PuntoVenta.WS_Info.UsuarioVO _token;
        
        public ConsultarProveedoresRequestBody() {
        }
        
        public ConsultarProveedoresRequestBody(PuntoVenta.WS_Info.UsuarioVO _token) {
            this._token = _token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarProveedoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarProveedoresResponse", Namespace="http://tempuri.org/", Order=0)]
        public PuntoVenta.WS_Info.ConsultarProveedoresResponseBody Body;
        
        public ConsultarProveedoresResponse() {
        }
        
        public ConsultarProveedoresResponse(PuntoVenta.WS_Info.ConsultarProveedoresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarProveedoresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PuntoVenta.WS_Info.ProveedorVO[] ConsultarProveedoresResult;
        
        public ConsultarProveedoresResponseBody() {
        }
        
        public ConsultarProveedoresResponseBody(PuntoVenta.WS_Info.ProveedorVO[] ConsultarProveedoresResult) {
            this.ConsultarProveedoresResult = ConsultarProveedoresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CompraNuevaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CompraNueva", Namespace="http://tempuri.org/", Order=0)]
        public PuntoVenta.WS_Info.CompraNuevaRequestBody Body;
        
        public CompraNuevaRequest() {
        }
        
        public CompraNuevaRequest(PuntoVenta.WS_Info.CompraNuevaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CompraNuevaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PuntoVenta.WS_Info.UsuarioVO _token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public PuntoVenta.WS_Info.Compra _compra;
        
        public CompraNuevaRequestBody() {
        }
        
        public CompraNuevaRequestBody(PuntoVenta.WS_Info.UsuarioVO _token, PuntoVenta.WS_Info.Compra _compra) {
            this._token = _token;
            this._compra = _compra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CompraNuevaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CompraNuevaResponse", Namespace="http://tempuri.org/", Order=0)]
        public PuntoVenta.WS_Info.CompraNuevaResponseBody Body;
        
        public CompraNuevaResponse() {
        }
        
        public CompraNuevaResponse(PuntoVenta.WS_Info.CompraNuevaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CompraNuevaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CompraNuevaResult;
        
        public CompraNuevaResponseBody() {
        }
        
        public CompraNuevaResponseBody(bool CompraNuevaResult) {
            this.CompraNuevaResult = CompraNuevaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VentaNuevaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VentaNueva", Namespace="http://tempuri.org/", Order=0)]
        public PuntoVenta.WS_Info.VentaNuevaRequestBody Body;
        
        public VentaNuevaRequest() {
        }
        
        public VentaNuevaRequest(PuntoVenta.WS_Info.VentaNuevaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VentaNuevaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PuntoVenta.WS_Info.UsuarioVO _token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public PuntoVenta.WS_Info.VentaVO _venta;
        
        public VentaNuevaRequestBody() {
        }
        
        public VentaNuevaRequestBody(PuntoVenta.WS_Info.UsuarioVO _token, PuntoVenta.WS_Info.VentaVO _venta) {
            this._token = _token;
            this._venta = _venta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VentaNuevaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VentaNuevaResponse", Namespace="http://tempuri.org/", Order=0)]
        public PuntoVenta.WS_Info.VentaNuevaResponseBody Body;
        
        public VentaNuevaResponse() {
        }
        
        public VentaNuevaResponse(PuntoVenta.WS_Info.VentaNuevaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VentaNuevaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VentaNuevaResult;
        
        public VentaNuevaResponseBody() {
        }
        
        public VentaNuevaResponseBody(bool VentaNuevaResult) {
            this.VentaNuevaResult = VentaNuevaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarVentasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarVentas", Namespace="http://tempuri.org/", Order=0)]
        public PuntoVenta.WS_Info.ConsultarVentasRequestBody Body;
        
        public ConsultarVentasRequest() {
        }
        
        public ConsultarVentasRequest(PuntoVenta.WS_Info.ConsultarVentasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarVentasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime _fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public short _tarjeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public short _web;
        
        public ConsultarVentasRequestBody() {
        }
        
        public ConsultarVentasRequestBody(System.DateTime _fecha, short _tarjeta, short _web) {
            this._fecha = _fecha;
            this._tarjeta = _tarjeta;
            this._web = _web;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarVentasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarVentasResponse", Namespace="http://tempuri.org/", Order=0)]
        public PuntoVenta.WS_Info.ConsultarVentasResponseBody Body;
        
        public ConsultarVentasResponse() {
        }
        
        public ConsultarVentasResponse(PuntoVenta.WS_Info.ConsultarVentasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarVentasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PuntoVenta.WS_Info.ConsultaVentaVO[] ConsultarVentasResult;
        
        public ConsultarVentasResponseBody() {
        }
        
        public ConsultarVentasResponseBody(PuntoVenta.WS_Info.ConsultaVentaVO[] ConsultarVentasResult) {
            this.ConsultarVentasResult = ConsultarVentasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_InfoSoapChannel : PuntoVenta.WS_Info.WS_InfoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_InfoSoapClient : System.ServiceModel.ClientBase<PuntoVenta.WS_Info.WS_InfoSoap>, PuntoVenta.WS_Info.WS_InfoSoap {
        
        public WS_InfoSoapClient() {
        }
        
        public WS_InfoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_InfoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_InfoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_InfoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVenta.WS_Info.ConsultarProductosResponse PuntoVenta.WS_Info.WS_InfoSoap.ConsultarProductos(PuntoVenta.WS_Info.ConsultarProductosRequest request) {
            return base.Channel.ConsultarProductos(request);
        }
        
        public PuntoVenta.WS_Info.ProductoVO[] ConsultarProductos(PuntoVenta.WS_Info.UsuarioVO _token) {
            PuntoVenta.WS_Info.ConsultarProductosRequest inValue = new PuntoVenta.WS_Info.ConsultarProductosRequest();
            inValue.Body = new PuntoVenta.WS_Info.ConsultarProductosRequestBody();
            inValue.Body._token = _token;
            PuntoVenta.WS_Info.ConsultarProductosResponse retVal = ((PuntoVenta.WS_Info.WS_InfoSoap)(this)).ConsultarProductos(inValue);
            return retVal.Body.ConsultarProductosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVenta.WS_Info.ConsultarProveedoresResponse PuntoVenta.WS_Info.WS_InfoSoap.ConsultarProveedores(PuntoVenta.WS_Info.ConsultarProveedoresRequest request) {
            return base.Channel.ConsultarProveedores(request);
        }
        
        public PuntoVenta.WS_Info.ProveedorVO[] ConsultarProveedores(PuntoVenta.WS_Info.UsuarioVO _token) {
            PuntoVenta.WS_Info.ConsultarProveedoresRequest inValue = new PuntoVenta.WS_Info.ConsultarProveedoresRequest();
            inValue.Body = new PuntoVenta.WS_Info.ConsultarProveedoresRequestBody();
            inValue.Body._token = _token;
            PuntoVenta.WS_Info.ConsultarProveedoresResponse retVal = ((PuntoVenta.WS_Info.WS_InfoSoap)(this)).ConsultarProveedores(inValue);
            return retVal.Body.ConsultarProveedoresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVenta.WS_Info.CompraNuevaResponse PuntoVenta.WS_Info.WS_InfoSoap.CompraNueva(PuntoVenta.WS_Info.CompraNuevaRequest request) {
            return base.Channel.CompraNueva(request);
        }
        
        public bool CompraNueva(PuntoVenta.WS_Info.UsuarioVO _token, PuntoVenta.WS_Info.Compra _compra) {
            PuntoVenta.WS_Info.CompraNuevaRequest inValue = new PuntoVenta.WS_Info.CompraNuevaRequest();
            inValue.Body = new PuntoVenta.WS_Info.CompraNuevaRequestBody();
            inValue.Body._token = _token;
            inValue.Body._compra = _compra;
            PuntoVenta.WS_Info.CompraNuevaResponse retVal = ((PuntoVenta.WS_Info.WS_InfoSoap)(this)).CompraNueva(inValue);
            return retVal.Body.CompraNuevaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVenta.WS_Info.VentaNuevaResponse PuntoVenta.WS_Info.WS_InfoSoap.VentaNueva(PuntoVenta.WS_Info.VentaNuevaRequest request) {
            return base.Channel.VentaNueva(request);
        }
        
        public bool VentaNueva(PuntoVenta.WS_Info.UsuarioVO _token, PuntoVenta.WS_Info.VentaVO _venta) {
            PuntoVenta.WS_Info.VentaNuevaRequest inValue = new PuntoVenta.WS_Info.VentaNuevaRequest();
            inValue.Body = new PuntoVenta.WS_Info.VentaNuevaRequestBody();
            inValue.Body._token = _token;
            inValue.Body._venta = _venta;
            PuntoVenta.WS_Info.VentaNuevaResponse retVal = ((PuntoVenta.WS_Info.WS_InfoSoap)(this)).VentaNueva(inValue);
            return retVal.Body.VentaNuevaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVenta.WS_Info.ConsultarVentasResponse PuntoVenta.WS_Info.WS_InfoSoap.ConsultarVentas(PuntoVenta.WS_Info.ConsultarVentasRequest request) {
            return base.Channel.ConsultarVentas(request);
        }
        
        public PuntoVenta.WS_Info.ConsultaVentaVO[] ConsultarVentas(System.DateTime _fecha, short _tarjeta, short _web) {
            PuntoVenta.WS_Info.ConsultarVentasRequest inValue = new PuntoVenta.WS_Info.ConsultarVentasRequest();
            inValue.Body = new PuntoVenta.WS_Info.ConsultarVentasRequestBody();
            inValue.Body._fecha = _fecha;
            inValue.Body._tarjeta = _tarjeta;
            inValue.Body._web = _web;
            PuntoVenta.WS_Info.ConsultarVentasResponse retVal = ((PuntoVenta.WS_Info.WS_InfoSoap)(this)).ConsultarVentas(inValue);
            return retVal.Body.ConsultarVentasResult;
        }
    }
}
